name: Update cve-feed-osv repo
on:
  schedule:
  - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update cve-feed-osv
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      REPOSITORY_OWNER: ${{ github.repository_owner }}
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Setup github user email and name
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: compile cve-feed-osv
      run: go build -o cve-feed-osv .

    - name: update cve-feed-osv advisory
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./scripts/create_pr.sh
